# -*- coding: utf-8 -*-
"""Exam Pass/Fail with Grade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LKKR64980Afz0GoV2Q7s5cquyGNE1vXv
"""

# Take marks as input:
# If marks ≥ 50 → Print "Pass"
# Else → Print "Fail"

#Also print grade:
# 80+ → A
# 70–79 → B
# 60–69 → C
# 50–59 → D
# Below 50 → F

marks = int (input ("Enter your marks"))

if marks >= 50:
  print ("Pass")
  if marks >= 80:
    print ("Grade A")
  elif marks >= 70:
    print ("Grade B")
  elif marks >= 60:
    print ("Grade C")
  elif marks >= 50:
    print ("Grade D")

else:
  print ("Fail")
  print ("Grade F")